<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Users Report</title>
</head>
<body>
    <div style="margin-bottom:25px;"><strong>Report generated by: </strong></div>
    <table style="border-collapse: collapse;">
        <thead>
            <tr>
                <th style="border-bottom:2pt solid black;">
                    <strong>ID</strong>
                </th>
                <th style="border-bottom:2pt solid black;">
                    <strong>Name</strong>
                </th>
                <th style="border-bottom:2pt solid black;">
                    <strong>Email</strong>
                </th>
            </tr>
        </thead>
        <tbody>
       
        </tbody>
    </table>
</body>
</html>